const n = 20;
const m = 88;
const vertices_orig = [
"Austria",
"Belgium",
"CzechRepublic",
"Denmark",
"Estonia",
"Finland",
"France",
"Germany",
"Greece",
"Italy",
"Netherlands",
"Norway",
"Poland",
"Russia",
"Sweden",
"Switzerland",
"Ukraine",
"UnitedKingdom",
"UnitedStates",
"empty"
];

const edges_orig = [
"Austria --> CzechRepublic",
"Austria --> Germany",
"Austria --> Italy",
"Austria --> UnitedStates",
"Belgium --> France",
"Belgium --> Germany",
"Belgium --> Italy",
"Belgium --> Netherlands",
"Belgium --> UnitedKingdom",
"CzechRepublic --> Austria",
"CzechRepublic --> empty",
"Denmark --> Germany",
"Denmark --> Netherlands",
"Estonia --> Germany",
"France --> Austria",
"France --> Belgium",
"France --> Germany",
"France --> Italy",
"France --> Netherlands",
"France --> Russia",
"France --> Switzerland",
"France --> Ukraine",
"France --> UnitedStates",
"France --> empty",
"Germany --> Austria",
"Germany --> Belgium",
"Germany --> Denmark",
"Germany --> Estonia",
"Germany --> Finland",
"Germany --> France",
"Germany --> Italy",
"Germany --> Netherlands",
"Germany --> Poland",
"Germany --> Russia",
"Germany --> Sweden",
"Germany --> Switzerland",
"Germany --> Ukraine",
"Germany --> UnitedKingdom",
"Germany --> UnitedStates",
"Germany --> empty",
"Greece --> Germany",
"Greece --> Italy",
"Italy --> Belgium",
"Italy --> France",
"Italy --> Germany",
"Italy --> Greece",
"Italy --> Netherlands",
"Italy --> Poland",
"Italy --> Switzerland",
"Italy --> empty",
"Netherlands --> Austria",
"Netherlands --> Belgium",
"Netherlands --> France",
"Netherlands --> Germany",
"Netherlands --> Italy",
"Netherlands --> Sweden",
"Netherlands --> Switzerland",
"Netherlands --> UnitedKingdom",
"Netherlands --> empty",
"Norway --> France",
"Norway --> Germany",
"Poland --> Germany",
"Sweden --> Finland",
"Sweden --> Germany",
"Sweden --> UnitedStates",
"Switzerland --> Germany",
"Switzerland --> Netherlands",
"Ukraine --> Russia",
"UnitedKingdom --> Germany",
"UnitedKingdom --> Italy",
"UnitedKingdom --> Netherlands",
"UnitedKingdom --> UnitedStates",
"UnitedKingdom --> empty",
"UnitedStates --> empty",
"empty --> Austria",
"empty --> Belgium",
"empty --> CzechRepublic",
"empty --> France",
"empty --> Germany",
"empty --> Greece",
"empty --> Italy",
"empty --> Netherlands",
"empty --> Norway",
"empty --> Poland",
"empty --> Russia",
"empty --> Switzerland",
"empty --> UnitedKingdom",
"empty --> UnitedStates"
];
